### PR TITLE
Update build system and add f/b keys

### PR DESCRIPTION
**Pull request by esmil**
Hi, nice little tool!

I've updated the Makefile so it should hopefully be a little more flexible for distro maintainers to use pkg-config and overwrite variables with make VAR=whatever.

I've tested it with and without pkg-config on buster, sid, focal, rawhide and Archlinux, but unfortunately I don't have access to a Mac so please test that before merging. Plain `make` should work exactly as before though.

### CODE REVIEW

**Comment by Titor8115** [comment]
@esmil HEY!!! I so glade someone with more distro makefile experience finally appeared! I'll test it out on the Mac tomorrow.

PS: I didn't use __has_include because overthinking constantly about backward compatibility. (silly me...)

**Comment by esmil** [comment]
Don't worry. Worrying about using `__has_include` is not necessarily silly. It just depends on how valuable you think it is that mandown works on old and/or weird systems that doesn't use either gcc or clang.

**Comment by Titor8115** [comment]
@esmil I did another test after realizing I set my mac's terminal to automatically connect to my VM Linux. It seems there an issue when running line 124 `-include $O/*.d $O/*/*.d` or line 132 `$O/%/:`

The error message is `make: *** build/*.d: Is a directory.  Stop.`
I did some search about this error, and it seems to be an issue with OS X's case sensitivity when using directory as value in makefile. I'm not sure if you are familiar with this. I'm still trying to find a solution.

**Comment by esmil** [comment]
Hmm.. interesting. Maybe try changing line 124 to
```
include $(wildcard $O/*.d $O/*/*.d)
```
and make line 132 more explicit with
```
$O/blender/ $O/parser/ $O/src/:
```

**Comment by Titor8115** [comment]
Yep, I think it was the line 124 that caused the problem. It's working now, I'm doing some additional test.
Thanks mate!

**Pull request merged**
